#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using ErrorLog.Core;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Logga/Details.cshtml")]
    public partial class _Views_Logga_Details_cshtml : System.Web.Mvc.WebViewPage<Logga.Entities.LoggaEntry>
    {
        public _Views_Logga_Details_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Logga\Details.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\n\n<!DOCTYPE html>\n<html>\n<head>\n    <title>Hi, I\'m Logga and i\'m your friend!</ti" +
"tle>\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(">\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\"");

WriteLiteral(">\n    <script");

WriteLiteral(" src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"");

WriteLiteral("></script>\n</head>\n\n<body");

WriteLiteral(" bgcolor=\"white\"");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\n    <div");

WriteLiteral(" class=\"navbar navbar-default navbar-fixed-top\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\n            <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"navbar-toggle\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-target=\".navbar-collapse\"");

WriteLiteral(">\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\n                </button>\n");

WriteLiteral("                ");

            
            #line 25 "..\..\Views\Logga\Details.cshtml"
           Write(Html.ActionLink("Back to Index", "Index", "Logga", new { area = "" }, new { @class = "navbar-brand" }));

            
            #line default
            #line hidden
WriteLiteral("\n            </div>\n        </div>\n    </div>\n    <br /><br />\n    <span>\n       " +
" <h1>Server Error in \'/\' Application.<hr");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" size=\"1\"");

WriteLiteral(" color=\"silver\"");

WriteLiteral("></h1>\n\n        ");

WriteLiteral("\n    </span>\n\n    <font");

WriteLiteral(" face=\"Arial, Helvetica, Geneva, SunSans-Regular, sans-serif \"");

WriteLiteral(">\n\n        <b> Description: </b>\n");

WriteLiteral("        ");

            
            #line 39 "..\..\Views\Logga\Details.cshtml"
   Write(Model.Message);

            
            #line default
            #line hidden
WriteLiteral("\n        <br /><br />\n\n        <b> Exception Details: </b>");

            
            #line 42 "..\..\Views\Logga\Details.cshtml"
                              Write(Model.Type);

            
            #line default
            #line hidden
WriteLiteral(": ");

            
            #line 42 "..\..\Views\Logga\Details.cshtml"
                                           Write(Model.Message);

            
            #line default
            #line hidden
WriteLiteral("<br>\n\n        ");

WriteLiteral("\n\n        <br>\n\n        <b> Source File: </b> ");

            
            #line 66 "..\..\Views\Logga\Details.cshtml"
                         Write(Model.Target);

            
            #line default
            #line hidden
WriteLiteral("\n        <br><br>\n\n        <b>Stack Trace:</b>\n\n        <table");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" bgcolor=\"#ffffcc\"");

WriteLiteral(">\n            <tbody>\n                <tr>\n                    <td>\n             " +
"           <pre>\n");

WriteLiteral("                             ");

            
            #line 76 "..\..\Views\Logga\Details.cshtml"
                        Write(Model.StackTrace);

            
            #line default
            #line hidden
WriteLiteral("\n                            </pre>\n                    </td>\n                </t" +
"r>\n            </tbody>\n        </table>\n\n        <br>\n        <b>Date:</b>&nbsp" +
";");

            
            #line 84 "..\..\Views\Logga\Details.cshtml"
                     Write(Model.DateError);

            
            #line default
            #line hidden
WriteLiteral("\n        <br /><br>\n\n        <b>User:</b>&nbsp;");

            
            #line 87 "..\..\Views\Logga\Details.cshtml"
                     Write(Model.User);

            
            #line default
            #line hidden
WriteLiteral("\n        <br /><br>\n\n        <b>Host:</b>&nbsp;");

            
            #line 90 "..\..\Views\Logga\Details.cshtml"
                     Write(Model.Host);

            
            #line default
            #line hidden
WriteLiteral("\n        <br /><br>\n    </font>\n</body>\n</html>\n");

        }
    }
}
#pragma warning restore 1591
